create or replace table po_tracker.vendor_mapping (
    po_name varchar(255),
    qb_name varchar(255),
    qb_check_name varchar(255),
    id varchar(50),
    tc_name varchar(255),
    similarity int,
    row_num int
);

create or replace table po_tracker.tracker (
    master_po_num varchar(255),
    status varchar(255),
    status_type varchar(50),
    brand varchar(255),
    po_type varchar(255),
    fg_po_association varchar(255),
    po_date date,
    vendor_sku varchar(255),
    sku varchar(255),
    sku_name varchar(1064),
    upc varchar(255),
    max_lead_time float,
    ship_date_lead_time date,
    ship_date_req date,
    ship_date_actual date,
    req_receipt_date date,
    delivery_date_actual date,
    invoice_due_date date,
    ship_from varchar(255),
    ship_from_id varchar(50),
    ship_to varchar(255),
    ship_to_id varchar(50),
    total_po_quantity_sku float,
    quantity float,
    quantity_received float,
    moq float, 
    per_unit_order float,
    per_unit_effective float,
    total float,
    payment_terms varchar(1064),
    pmt_upfront_percent float,
    pmt_upfront_net int,
    pmt_upfront_addl_percent float,
    pmt_upfront_addl_net int, 
    pmt_ship_percent float,
    pmt_ship_net int,
    pmt_delivery_percent float,
    pmt_delivery_net int,
    pmt_cc boolean,
    pmt_cc_percent float,
    pmt_check boolean,
    new_launch boolean,
    launch_date date,
    latest boolean,
    _row_id varchar(255),
    _line int,
    _fivetran_synced timestamp_tz(9)
);

create or replace table po_tracker.average_price (
    sku varchar(255),
    sku_name varchar(255),
    product_type varchar(50),
    upc varchar(255),
    brand varchar(255),
    status varchar(50),
    vendor varchar(255),
    vendor_id varchar(50),
    average_price_order float,
    average_price_effective float,
    average_per_unit float,
    order_effective_delta float,
    average_price float,
    price_effective_from date,
    price_effective_to date,
    last_updated date,
    latest boolean
);

create or replace table po_status (
    status varchar(255),
    type varchar(255)
);