CREATE OR REPLACE TASK clone_google_tables
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '360 MINUTE'
AS
BEGIN
    CREATE OR REPLACE TABLE GOOGLE_ADS.ACCOUNTS
    AS SELECT * FROM PC_FIVETRAN_DB.GOOGLE_ADS_GOOGLE_ADS.GOOGLE_ADS__ACCOUNT_REPORT;

    CREATE OR REPLACE TABLE GOOGLE_ADS.AD_GROUPS
    AS SELECT * FROM PC_FIVETRAN_DB.GOOGLE_ADS_GOOGLE_ADS.GOOGLE_ADS__AD_GROUP_REPORT;

    CREATE OR REPLACE TABLE GOOGLE_ADS.CAMPAIGNS
    AS SELECT * FROM PC_FIVETRAN_DB.GOOGLE_ADS_GOOGLE_ADS.GOOGLE_ADS__CAMPAIGN_REPORT;

    CREATE OR REPLACE TABLE GOOGLE_ADS.ADS
    AS SELECT * FROM PC_FIVETRAN_DB.GOOGLE_ADS_GOOGLE_ADS.GOOGLE_ADS__AD_REPORT;

    CREATE OR REPLACE TABLE GOOGLE_ADS.KEYWORDS
    AS SELECT * FROM PC_FIVETRAN_DB.GOOGLE_ADS_GOOGLE_ADS.GOOGLE_ADS__KEYWORD_REPORT;

    CREATE OR REPLACE TABLE GOOGLE_ADS.URL
    AS SELECT * FROM PC_FIVETRAN_DB.GOOGLE_ADS_GOOGLE_ADS.GOOGLE_ADS__URL_REPORT;

    GRANT USAGE ON DATABASE PROD_SF_TABLES TO ROLE SF_USER;
    GRANT USAGE ON SCHEMA GOOGLE_ADS TO ROLE SF_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA GOOGLE_ADS TO ROLE SF_USER;

END;

ALTER TASK clone_google_tables
  RESUME;

grant accountadmin to jocelyn;